### ISSUE TITLE
DBの各種暗号化について

### ISSUE THREAD

**Issue by kyoya0819** [kai0310/OpinionBox#71]
現状、氏名やメールアドレスなどが暗号化との保護がされておらず、万が一DBが漏洩した際に非常に脆弱なつくりになっている。

少なくとも、以下を行うべきだと考える。
-  `name`を`encrypt()`で暗号化
-  `email`を`encrypt()`で暗号化
-  `hash_email`を`hash()`でハッシュ化し、unique制限やログイン時はこちらを使用

**Comment by kyoya0819** [comment]
対応します。

**Comment by kai0310** [comment]
@kyoya0819 
ありがとうございます。こちら認証にはパッケージを利用しておりそのままの仕様でした。
仰る通り暗号化を行った方がセキュアではありますね。。

**Comment by kai0310** [comment]
全ユーザーの名前検索とかあるので、とりあえずは良さそう、、？
