### ISSUE TITLE
ユーザのロールに関するDB構造について

### ISSUE THREAD

**Issue by kyoya0819** [kai0310/OpinionBox#72]
現状、usersには、`is_admin`カラムと、`is_developer`カラムが存在する。
しかし、将来的に新たに役割が増加する場合、テーブルを編集する必要がある。
一つのアカウントが複数の役割を持たないのであれば、usersの親に`authorizations`テーブルを作成することが望ましいと考える。

**Comment by kai0310** [comment]
ありがとうございます。
現状では役割が二つしか存在しないため今のような形になっており，一つのアカウントが複数の役割を持つことも想定しています。

今後としては，様々な人が利用するケースを想定しているのでカスタマイズをできるようにと考えています。その際にこちらも合わせて検討したいと思います。

**Comment by kai0310** [comment]
複数の権限があった方が良さそうな気がしてきたので、

- users
  ユーザ情報
- role_user
- roles
  ロール情報

が良さそう？？

**Comment by kai0310** [comment]
@kyoya0819 thanks :)
